# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: bookdown

jobs:
  bookdown:
    name: Render my document
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","readr","here"))'

      - name: Build site
        run: bookdown::render_book("index.Rmd", quiet = TRUE)

      - name: Commit results
        run: |
          git add *
          git commit -m 'Re-build my-documents' || echo "No changes to commit"
          git push origin || echo "No changes to commit"