on:
  push:
     branches:
       - master

  

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","readr","here"))'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v2
        with:
          name: _docs
          path: _docs/
  
# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
         # Artifact name
         name: _docs # optional
         # Destination path
         path: _docs # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
          GH_TOKEN: ${{ secrets.GH_PAT }} # https://github.com/settings/tokens
       with:
          EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
          BUILD_DIR: _book/                     # "_site/" by default
    
 
